// Code generated from SPDX license list v1ff5448; DO NOT EDIT.

package common

// spdxNameToID maps normalized (lowercased) SPDX license names to their
// canonical SPDX license identifiers.
var spdxNameToID = map[string]string{
	"3d slicer license v1.0": "3D-Slicer-1.0",
	"3dfx glide license": "Glide",
	"abstyles license": "Abstyles",
	"academic free license v1.1": "AFL-1.1",
	"academic free license v1.2": "AFL-1.2",
	"academic free license v2.0": "AFL-2.0",
	"academic free license v2.1": "AFL-2.1",
	"academic free license v3.0": "AFL-3.0",
	"academy of motion picture arts and sciences bsd": "AMPAS",
	"adacore doc license": "AdaCore-doc",
	"adaptive public license 1.0": "APL-1.0",
	"adobe display postscript license": "Adobe-Display-PostScript",
	"adobe glyph list license": "Adobe-Glyph",
	"adobe postscript afm license": "APAFML",
	"adobe systems incorporated source code license agreement": "Adobe-2006",
	"adobe utopia font license": "Adobe-Utopia",
	"advanced cryptics dictionary license": "Advanced-Cryptics-Dictionary",
	"affero general public license v1.0": "AGPL-1.0",
	"affero general public license v1.0 only": "AGPL-1.0-only",
	"affero general public license v1.0 or later": "AGPL-1.0-or-later",
	"afmparse license": "Afmparse",
	"aladdin free public license": "Aladdin",
	"alglib documentation license": "ALGLIB-Documentation",
	"amazon digital services license": "ADSL",
	"amd newlib license": "AMD-newlib",
	"amd's plpa_map.c license": "AMDPLPA",
	"aml glslang variant license": "AML-glslang",
	"antlr software rights notice": "ANTLR-PD",
	"antlr software rights notice with license fallback": "ANTLR-PD-fallback",
	"any osi license": "any-OSI",
	"any osi license - perl modules": "any-OSI-perl-modules",
	"apache license 1.0": "Apache-1.0",
	"apache license 1.1": "Apache-1.1",
	"apache license 2.0": "Apache-2.0",
	"app::s2p license": "App-s2p",
	"apple mit license": "AML",
	"apple public source license 1.0": "APSL-1.0",
	"apple public source license 1.1": "APSL-1.1",
	"apple public source license 1.2": "APSL-1.2",
	"apple public source license 2.0": "APSL-2.0",
	"arphic public license": "Arphic-1999",
	"artistic license 1.0": "Artistic-1.0",
	"artistic license 1.0 (dist)": "Artistic-dist",
	"artistic license 1.0 (perl)": "Artistic-1.0-Perl",
	"artistic license 1.0 w/clause 8": "Artistic-1.0-cl8",
	"artistic license 2.0": "Artistic-2.0",
	"aspell russian license": "Aspell-RU",
	"aswf digital assets license 1.1": "ASWF-Digital-Assets-1.1",
	"aswf digital assets license version 1.0": "ASWF-Digital-Assets-1.0",
	"attribution assurance license": "AAL",
	"baekmuk license": "Baekmuk",
	"bahyph license": "Bahyph",
	"barr license": "Barr",
	"bcrypt solar designer license": "bcrypt-Solar-Designer",
	"beerware license": "Beerware",
	"bitstream charter font license": "Bitstream-Charter",
	"bitstream vera font license": "Bitstream-Vera",
	"bittorrent open source license v1.0": "BitTorrent-1.0",
	"bittorrent open source license v1.1": "BitTorrent-1.1",
	"blue oak model license 1.0.0": "BlueOak-1.0.0",
	"boehm-demers-weiser gc license": "Boehm-GC",
	"boehm-demers-weiser gc license (without fee)": "Boehm-GC-without-fee",
	"boost software license 1.0": "BSL-1.0",
	"borceux license": "Borceux",
	"brian gladman 2-clause license": "Brian-Gladman-2-Clause",
	"brian gladman 3-clause license": "Brian-Gladman-3-Clause",
	"bsd 1-clause license": "BSD-1-Clause",
	"bsd 2-clause \"simplified\" license": "BSD-2-Clause",
	"bsd 2-clause - first lines requirement": "BSD-2-Clause-first-lines",
	"bsd 2-clause - ian darwin variant": "BSD-2-Clause-Darwin",
	"bsd 2-clause freebsd license": "BSD-2-Clause-FreeBSD",
	"bsd 2-clause netbsd license": "BSD-2-Clause-NetBSD",
	"bsd 2-clause pkgconf disclaimer variant": "BSD-2-Clause-pkgconf-disclaimer",
	"bsd 2-clause with views sentence": "BSD-2-Clause-Views",
	"bsd 3-clause \"new\" or \"revised\" license": "BSD-3-Clause",
	"bsd 3-clause acpica variant": "BSD-3-Clause-acpica",
	"bsd 3-clause clear license": "BSD-3-Clause-Clear",
	"bsd 3-clause flex variant": "BSD-3-Clause-flex",
	"bsd 3-clause modification": "BSD-3-Clause-Modification",
	"bsd 3-clause no military license": "BSD-3-Clause-No-Military-License",
	"bsd 3-clause no nuclear license": "BSD-3-Clause-No-Nuclear-License",
	"bsd 3-clause no nuclear license 2014": "BSD-3-Clause-No-Nuclear-License-2014",
	"bsd 3-clause no nuclear warranty": "BSD-3-Clause-No-Nuclear-Warranty",
	"bsd 3-clause open mpi variant": "BSD-3-Clause-Open-MPI",
	"bsd 3-clause sun microsystems": "BSD-3-Clause-Sun",
	"bsd 3-clause tso variant": "BSD-3-Clause-Tso",
	"bsd 4 clause shortened": "BSD-4-Clause-Shortened",
	"bsd 4-clause \"original\" or \"old\" license": "BSD-4-Clause",
	"bsd 4.3 reno license": "BSD-4.3RENO",
	"bsd 4.3 tahoe license": "BSD-4.3TAHOE",
	"bsd advertising acknowledgement license": "BSD-Advertising-Acknowledgement",
	"bsd mark modifications license": "BSD-Mark-Modifications",
	"bsd protection license": "BSD-Protection",
	"bsd source code attribution": "BSD-Source-Code",
	"bsd source code attribution - beginning of file variant": "BSD-Source-beginning-file",
	"bsd with attribution": "BSD-3-Clause-Attribution",
	"bsd with attribution and hpnd disclaimer": "BSD-Attribution-HPND-disclaimer",
	"bsd zero clause license": "0BSD",
	"bsd-2-clause plus patent license": "BSD-2-Clause-Patent",
	"bsd-4-clause (university of california-specific)": "BSD-4-Clause-UC",
	"bsd-inferno-nettverk": "BSD-Inferno-Nettverk",
	"buddy license": "Buddy",
	"buena onda license agreement v1.1": "BOLA-1.1",
	"business source license 1.1": "BUSL-1.1",
	"bzip2 and libbzip2 license v1.0.5": "bzip2-1.0.5",
	"bzip2 and libbzip2 license v1.0.6": "bzip2-1.0.6",
	"caldera license": "Caldera",
	"caldera license (without preamble)": "Caldera-no-preamble",
	"catharon license": "Catharon",
	"cecill free software license agreement v1.0": "CECILL-1.0",
	"cecill free software license agreement v1.1": "CECILL-1.1",
	"cecill free software license agreement v2.0": "CECILL-2.0",
	"cecill free software license agreement v2.1": "CECILL-2.1",
	"cecill-b free software license agreement": "CECILL-B",
	"cecill-c free software license agreement": "CECILL-C",
	"cern open hardware licence v1.1": "CERN-OHL-1.1",
	"cern open hardware licence v1.2": "CERN-OHL-1.2",
	"cern open hardware licence version 2 - permissive": "CERN-OHL-P-2.0",
	"cern open hardware licence version 2 - strongly reciprocal": "CERN-OHL-S-2.0",
	"cern open hardware licence version 2 - weakly reciprocal": "CERN-OHL-W-2.0",
	"cfitsio license": "CFITSIO",
	"check-cvs license": "check-cvs",
	"checkmk license": "checkmk",
	"clarified artistic license": "ClArtistic",
	"clips license": "Clips",
	"cmu    mach - no notices-in-documentation variant": "CMU-Mach-nodoc",
	"cmu license": "MIT-CMU",
	"cmu mach license": "CMU-Mach",
	"cnri jython license": "CNRI-Jython",
	"cnri python license": "CNRI-Python",
	"cnri python open source gpl compatible license agreement": "CNRI-Python-GPL-Compatible",
	"code project open license 1.02": "CPOL-1.02",
	"common attack    pattern enumeration and classification license": "CAPEC-tou",
	"common development and distribution license 1.0": "CDDL-1.0",
	"common development and distribution license 1.1": "CDDL-1.1",
	"common documentation license 1.0": "CDL-1.0",
	"common lisp loop license": "LOOP",
	"common public attribution license 1.0": "CPAL-1.0",
	"common public license 1.0": "CPL-1.0",
	"common vulnerability enumeration tou license": "cve-tou",
	"community data license agreement permissive 1.0": "CDLA-Permissive-1.0",
	"community data license agreement permissive 2.0": "CDLA-Permissive-2.0",
	"community data license agreement sharing 1.0": "CDLA-Sharing-1.0",
	"community specification license 1.0": "Community-Spec-1.0",
	"computational use of data agreement v1.0": "C-UDA-1.0",
	"computer associates trusted open source license 1.1": "CATOSL-1.1",
	"condor public license v1.1": "Condor-1.1",
	"copyfree open innovation license": "COIL-1.0",
	"copyleft-next 0.3.0": "copyleft-next-0.3.0",
	"copyleft-next 0.3.1": "copyleft-next-0.3.1",
	"cornell lossless jpeg license": "Cornell-Lossless-JPEG",
	"creative    commons public domain mark 1.0 universal": "CC-PDM-1.0",
	"creative commons attribution 1.0 generic": "CC-BY-1.0",
	"creative commons attribution 2.0 generic": "CC-BY-2.0",
	"creative commons attribution 2.5 australia": "CC-BY-2.5-AU",
	"creative commons attribution 2.5 generic": "CC-BY-2.5",
	"creative commons attribution 3.0 australia": "CC-BY-3.0-AU",
	"creative commons attribution 3.0 austria": "CC-BY-3.0-AT",
	"creative commons attribution 3.0 germany": "CC-BY-3.0-DE",
	"creative commons attribution 3.0 igo": "CC-BY-3.0-IGO",
	"creative commons attribution 3.0 netherlands": "CC-BY-3.0-NL",
	"creative commons attribution 3.0 united states": "CC-BY-3.0-US",
	"creative commons attribution 3.0 unported": "CC-BY-3.0",
	"creative commons attribution 4.0 international": "CC-BY-4.0",
	"creative commons attribution no derivatives 1.0 generic": "CC-BY-ND-1.0",
	"creative commons attribution no derivatives 2.0 generic": "CC-BY-ND-2.0",
	"creative commons attribution no derivatives 2.5 generic": "CC-BY-ND-2.5",
	"creative commons attribution no derivatives 3.0 germany": "CC-BY-ND-3.0-DE",
	"creative commons attribution no derivatives 3.0 unported": "CC-BY-ND-3.0",
	"creative commons attribution no derivatives 4.0 international": "CC-BY-ND-4.0",
	"creative commons attribution non commercial 1.0 generic": "CC-BY-NC-1.0",
	"creative commons attribution non commercial 2.0 generic": "CC-BY-NC-2.0",
	"creative commons attribution non commercial 2.5 generic": "CC-BY-NC-2.5",
	"creative commons attribution non commercial 3.0 germany": "CC-BY-NC-3.0-DE",
	"creative commons attribution non commercial 3.0 unported": "CC-BY-NC-3.0",
	"creative commons attribution non commercial 4.0 international": "CC-BY-NC-4.0",
	"creative commons attribution non commercial no derivatives 1.0 generic": "CC-BY-NC-ND-1.0",
	"creative commons attribution non commercial no derivatives 2.0 generic": "CC-BY-NC-ND-2.0",
	"creative commons attribution non commercial no derivatives 2.5 generic": "CC-BY-NC-ND-2.5",
	"creative commons attribution non commercial no derivatives 3.0 germany": "CC-BY-NC-ND-3.0-DE",
	"creative commons attribution non commercial no derivatives 3.0 igo": "CC-BY-NC-ND-3.0-IGO",
	"creative commons attribution non commercial no derivatives 3.0 unported": "CC-BY-NC-ND-3.0",
	"creative commons attribution non commercial no derivatives 4.0 international": "CC-BY-NC-ND-4.0",
	"creative commons attribution non commercial share alike 1.0 generic": "CC-BY-NC-SA-1.0",
	"creative commons attribution non commercial share alike 2.0 england and wales": "CC-BY-NC-SA-2.0-UK",
	"creative commons attribution non commercial share alike 2.0 generic": "CC-BY-NC-SA-2.0",
	"creative commons attribution non commercial share alike 2.0 germany": "CC-BY-NC-SA-2.0-DE",
	"creative commons attribution non commercial share alike 2.5 generic": "CC-BY-NC-SA-2.5",
	"creative commons attribution non commercial share alike 3.0 germany": "CC-BY-NC-SA-3.0-DE",
	"creative commons attribution non commercial share alike 3.0 igo": "CC-BY-NC-SA-3.0-IGO",
	"creative commons attribution non commercial share alike 3.0 unported": "CC-BY-NC-SA-3.0",
	"creative commons attribution non commercial share alike 4.0 international": "CC-BY-NC-SA-4.0",
	"creative commons attribution share alike 1.0 generic": "CC-BY-SA-1.0",
	"creative commons attribution share alike 2.0 england and wales": "CC-BY-SA-2.0-UK",
	"creative commons attribution share alike 2.0 generic": "CC-BY-SA-2.0",
	"creative commons attribution share alike 2.1 japan": "CC-BY-SA-2.1-JP",
	"creative commons attribution share alike 2.5 generic": "CC-BY-SA-2.5",
	"creative commons attribution share alike 3.0 austria": "CC-BY-SA-3.0-AT",
	"creative commons attribution share alike 3.0 germany": "CC-BY-SA-3.0-DE",
	"creative commons attribution share alike 3.0 unported": "CC-BY-SA-3.0",
	"creative commons attribution share alike 4.0 international": "CC-BY-SA-4.0",
	"creative commons attribution-noncommercial-sharealike 2.0 france": "CC-BY-NC-SA-2.0-FR",
	"creative commons attribution-sharealike 3.0 igo": "CC-BY-SA-3.0-IGO",
	"creative commons public domain dedication and certification": "CC-PDDC",
	"creative commons share alike 1.0 generic": "CC-SA-1.0",
	"creative commons zero v1.0 universal": "CC0-1.0",
	"cronyx license": "Cronyx",
	"crossword license": "Crossword",
	"cryptographic autonomy license 1.0": "CAL-1.0",
	"cryptographic autonomy license 1.0 (combined work exception)": "CAL-1.0-Combined-Work-Exception",
	"cryptoswift license": "CryptoSwift",
	"crystalstacker license": "CrystalStacker",
	"cua office public license v1.0": "CUA-OPL-1.0",
	"cube license": "Cube",
	"curl license": "curl",
	"data licence germany – attribution – version 2.0": "DL-DE-BY-2.0",
	"data licence germany – zero – version 2.0": "DL-DE-ZERO-2.0",
	"david m. gay dtoa license": "dtoa",
	"dec 3-clause license": "DEC-3-Clause",
	"detection rule license 1.0": "DRL-1.0",
	"detection rule license 1.1": "DRL-1.1",
	"deutsche freie software lizenz": "D-FSL-1.0",
	"diffmark license": "diffmark",
	"do what the f*ck you want to but it's not my fault public license": "WTFNMFPL",
	"do what the f*ck you want to public license": "WTFPL",
	"doc license": "DOC",
	"docbook dtd license": "DocBook-DTD",
	"docbook schema license": "DocBook-Schema",
	"docbook stylesheet license": "DocBook-Stylesheet",
	"docbook xml license": "DocBook-XML",
	"dotseqn license": "Dotseqn",
	"dsdp license": "DSDP",
	"dvipdfm license": "dvipdfm",
	"eclipse public license 1.0": "EPL-1.0",
	"eclipse public license 2.0": "EPL-2.0",
	"ecos license version 2.0": "eCos-2.0",
	"educational community license v1.0": "ECL-1.0",
	"educational community license v2.0": "ECL-2.0",
	"egenix.com public license 1.1.0": "eGenix",
	"eiffel forum license v1.0": "EFL-1.0",
	"eiffel forum license v2.0": "EFL-2.0",
	"elastic license 2.0": "Elastic-2.0",
	"enlightenment license (e16)": "MIT-advertising",
	"enna license": "MIT-enna",
	"entessa public license v1.0": "Entessa",
	"epics open license": "EPICS",
	"erlang public license v1.1": "ErlPL-1.1",
	"etalab open license 2.0": "etalab-2.0",
	"eu datagrid software license": "EUDatagrid",
	"european space agency public license (esa-pl) - v2.4 - strong copyleft (type 1)": "ESA-PL-strong-copyleft-2.4",
	"european space agency public license – v2.4 – permissive (type 3)": "ESA-PL-permissive-2.4",
	"european space agency public license – v2.4 – weak copyleft (type 2)": "ESA-PL-weak-copyleft-2.4",
	"european union public license 1.0": "EUPL-1.0",
	"european union public license 1.1": "EUPL-1.1",
	"european union public license 1.2": "EUPL-1.2",
	"eurosym license": "Eurosym",
	"fair license": "Fair",
	"feh license": "MIT-feh",
	"ferguson twofish license": "Ferguson-Twofish",
	"frameworx open license 1.0": "Frameworx-1.0",
	"fraunhofer fdk aac codec library": "FDK-AAC",
	"freebsd documentation license": "FreeBSD-DOC",
	"freeimage public license v1.0": "FreeImage",
	"freetype project license": "FTL",
	"fsf all permissive license": "FSFAP",
	"fsf all permissive license (without warranty)": "FSFAP-no-warranty-disclaimer",
	"fsf unlimited license": "FSFUL",
	"fsf unlimited license (with license retention and short disclaimer)": "FSFULLRSD",
	"fsf unlimited license (with license retention and warranty disclaimer)": "FSFULLRWD",
	"fsf unlimited license (with license retention)": "FSFULLR",
	"functional source license, version 1.1, alv2 future license": "FSL-1.1-ALv2",
	"functional source license, version 1.1, mit future license": "FSL-1.1-MIT",
	"furuseth license": "Furuseth",
	"fuzzy bitmap license": "FBM",
	"fwlw license": "fwlw",
	"game programming gems license": "Game-Programming-Gems",
	"gd license": "GD",
	"generic xts license": "generic-xts",
	"giftware license": "Giftware",
	"gl2ps license": "GL2PS",
	"glulxe license": "Glulxe",
	"gnome gcr documentation license": "GCR-docs",
	"gnu affero general public license v3.0": "AGPL-3.0",
	"gnu affero general public license v3.0 only": "AGPL-3.0-only",
	"gnu affero general public license v3.0 or later": "AGPL-3.0-or-later",
	"gnu free documentation license v1.1": "GFDL-1.1",
	"gnu free documentation license v1.1 only": "GFDL-1.1-only",
	"gnu free documentation license v1.1 only - invariants": "GFDL-1.1-invariants-only",
	"gnu free documentation license v1.1 only - no invariants": "GFDL-1.1-no-invariants-only",
	"gnu free documentation license v1.1 or later": "GFDL-1.1-or-later",
	"gnu free documentation license v1.1 or later - invariants": "GFDL-1.1-invariants-or-later",
	"gnu free documentation license v1.1 or later - no invariants": "GFDL-1.1-no-invariants-or-later",
	"gnu free documentation license v1.2": "GFDL-1.2",
	"gnu free documentation license v1.2 only": "GFDL-1.2-only",
	"gnu free documentation license v1.2 only - invariants": "GFDL-1.2-invariants-only",
	"gnu free documentation license v1.2 only - no invariants": "GFDL-1.2-no-invariants-only",
	"gnu free documentation license v1.2 or later": "GFDL-1.2-or-later",
	"gnu free documentation license v1.2 or later - invariants": "GFDL-1.2-invariants-or-later",
	"gnu free documentation license v1.2 or later - no invariants": "GFDL-1.2-no-invariants-or-later",
	"gnu free documentation license v1.3": "GFDL-1.3",
	"gnu free documentation license v1.3 only": "GFDL-1.3-only",
	"gnu free documentation license v1.3 only - invariants": "GFDL-1.3-invariants-only",
	"gnu free documentation license v1.3 only - no invariants": "GFDL-1.3-no-invariants-only",
	"gnu free documentation license v1.3 or later": "GFDL-1.3-or-later",
	"gnu free documentation license v1.3 or later - invariants": "GFDL-1.3-invariants-or-later",
	"gnu free documentation license v1.3 or later - no invariants": "GFDL-1.3-no-invariants-or-later",
	"gnu general public license v1.0 only": "GPL-1.0-only",
	"gnu general public license v1.0 or later": "GPL-1.0-or-later",
	"gnu general public license v2.0 only": "GPL-2.0-only",
	"gnu general public license v2.0 or later": "GPL-2.0-or-later",
	"gnu general public license v2.0 w/autoconf exception": "GPL-2.0-with-autoconf-exception",
	"gnu general public license v2.0 w/bison exception": "GPL-2.0-with-bison-exception",
	"gnu general public license v2.0 w/classpath exception": "GPL-2.0-with-classpath-exception",
	"gnu general public license v2.0 w/font exception": "GPL-2.0-with-font-exception",
	"gnu general public license v2.0 w/gcc runtime library exception": "GPL-2.0-with-GCC-exception",
	"gnu general public license v3.0 only": "GPL-3.0-only",
	"gnu general public license v3.0 or later": "GPL-3.0-or-later",
	"gnu general public license v3.0 w/autoconf exception": "GPL-3.0-with-autoconf-exception",
	"gnu general public license v3.0 w/gcc runtime library exception": "GPL-3.0-with-GCC-exception",
	"gnu lesser general public license v2.1 only": "LGPL-2.1-only",
	"gnu lesser general public license v2.1 or later": "LGPL-2.1-or-later",
	"gnu lesser general public license v3.0 only": "LGPL-3.0-only",
	"gnu lesser general public license v3.0 or later": "LGPL-3.0-or-later",
	"gnu library general public license v2 only": "LGPL-2.0-only",
	"gnu library general public license v2 or later": "LGPL-2.0-or-later",
	"gnuplot license": "gnuplot",
	"good luck with that public license": "GLWTPL",
	"graphics gems license": "Graphics-Gems",
	"gsoap public license v1.3b": "gSOAP-1.3b",
	"gtkbook license": "gtkbook",
	"gutmann license": "Gutmann",
	"haskell language report license": "HaskellReport",
	"hdf5 license": "HDF5",
	"hdparm license": "hdparm",
	"hewlett-packard 1986 license": "HP-1986",
	"hewlett-packard 1989 license": "HP-1989",
	"hewlett-packard bsd variant license": "BSD-3-Clause-HP",
	"hidapi license": "HIDAPI",
	"hippocratic license 2.1": "Hippocratic-2.1",
	"historical permission notice and disclaimer": "HPND",
	"historical permission notice and disclaimer    - inria-imag variant": "HPND-INRIA-IMAG",
	"historical permission notice and disclaimer - dec variant": "HPND-DEC",
	"historical permission notice and disclaimer - documentation sell variant": "HPND-doc-sell",
	"historical permission notice and disclaimer - documentation variant": "HPND-doc",
	"historical permission notice and disclaimer - fenneberg-livingston variant": "HPND-Fenneberg-Livingston",
	"historical permission notice and disclaimer - intel variant": "HPND-Intel",
	"historical permission notice and disclaimer - kevlin henney variant": "HPND-Kevlin-Henney",
	"historical permission notice and disclaimer - markus kuhn variant": "HPND-Markus-Kuhn",
	"historical permission notice and disclaimer - merchantability variant": "HPND-merchantability-variant",
	"historical permission notice and disclaimer - netrek variant": "HPND-Netrek",
	"historical permission notice and disclaimer - pbmplus variant": "HPND-Pbmplus",
	"historical permission notice and disclaimer - sell regexpr variant": "HPND-sell-regexpr",
	"historical permission notice and disclaimer - sell variant": "HPND-sell-variant",
	"historical permission notice and disclaimer - sell xserver variant with mit disclaimer": "HPND-sell-MIT-disclaimer-xserver",
	"historical permission notice and disclaimer - smc variant": "HPND-SMC",
	"historical permission notice and disclaimer - university of california variant": "HPND-UC",
	"historical permission notice and disclaimer - university of california, us export warning": "HPND-UC-export-US",
	"historical permission notice and disclaimer with mit disclaimer": "HPND-MIT-disclaimer",
	"hpnd - sell variant with safety critical systems clause": "HPND-sell-variant-critical-systems",
	"hpnd sell variant with mit disclaimer": "HPND-sell-variant-MIT-disclaimer",
	"hpnd sell variant with mit disclaimer - reverse": "HPND-sell-variant-MIT-disclaimer-rev",
	"hpnd with us government export control and 2 disclaimers": "HPND-export2-US",
	"hpnd with us government export control warning": "HPND-export-US",
	"hpnd with us government export control warning and acknowledgment": "HPND-export-US-acknowledgement",
	"hpnd with us government export control warning and modification rqmt": "HPND-export-US-modify",
	"html tidy license": "HTMLTIDY",
	"hyphen-bulgarian license": "hyphen-bulgarian",
	"ibm powerpc initialization and boot software": "IBM-pibs",
	"ibm public license v1.0": "IPL-1.0",
	"icu license": "ICU",
	"iec    code components end-user licence agreement": "IEC-Code-Components-EULA",
	"imagemagick license": "ImageMagick",
	"imatix standard function library agreement": "iMatix",
	"imlib2 license": "Imlib2",
	"independent jpeg group license": "IJG",
	"independent jpeg group license - short": "IJG-short",
	"info-zip license": "Info-ZIP",
	"inner net license v2.0": "Inner-Net-2.0",
	"inno setup license": "InnoSetup",
	"intel acpi software license agreement": "Intel-ACPI",
	"intel open source license": "Intel",
	"interbase public license v1.0": "Interbase-1.0",
	"ipa font license": "IPA",
	"isc license": "ISC",
	"isc veillard variant": "ISC-Veillard",
	"iso permission notice": "ISO-permission",
	"jam license": "Jam",
	"japan network information center license": "JPNIC",
	"jasper license": "JasPer-2.0",
	"jove license": "jove",
	"jpl image use policy": "JPL-image",
	"json license": "JSON",
	"kastrup license": "Kastrup",
	"kazlib license": "Kazlib",
	"knuth ctan license": "Knuth-CTAN",
	"latex project public license v1.0": "LPPL-1.0",
	"latex project public license v1.1": "LPPL-1.1",
	"latex project public license v1.2": "LPPL-1.2",
	"latex project public license v1.3a": "LPPL-1.3a",
	"latex project public license v1.3c": "LPPL-1.3c",
	"latex2e license": "Latex2e",
	"latex2e with translated notice permission": "Latex2e-translated-notice",
	"lawrence berkeley national labs bsd variant license": "BSD-3-Clause-LBNL",
	"leptonica license": "Leptonica",
	"lesser general public license for linguistic resources": "LGPLLR",
	"libpng license": "Libpng",
	"libselinux public domain notice": "libselinux-1.0",
	"libtiff license": "libtiff",
	"libutil david nugent license": "libutil-David-Nugent",
	"licence art libre 1.2": "LAL-1.2",
	"licence art libre 1.3": "LAL-1.3",
	"licence libre du québec – permissive version 1.1": "LiLiQ-P-1.1",
	"licence libre du québec – réciprocité forte version 1.1": "LiLiQ-Rplus-1.1",
	"licence libre du québec – réciprocité version 1.1": "LiLiQ-R-1.1",
	"linux kernel variant of openib.org license": "Linux-OpenIB",
	"linux man-pages - 1 paragraph": "Linux-man-pages-1-para",
	"linux man-pages copyleft": "Linux-man-pages-copyleft",
	"linux man-pages copyleft - 2 paragraphs": "Linux-man-pages-copyleft-2-para",
	"linux man-pages copyleft variant": "Linux-man-pages-copyleft-var",
	"lpd documentation license": "LPD-document",
	"lsof license": "lsof",
	"lucent public license v1.02": "LPL-1.02",
	"lucent public license version 1.0": "LPL-1.0",
	"lucida bitmap fonts license": "Lucida-Bitmap-Fonts",
	"lzma sdk license (versions 9.11 to 9.20)": "LZMA-SDK-9.11-to-9.20",
	"lzma sdk license (versions 9.22 and beyond)": "LZMA-SDK-9.22",
	"mackerras 3-clause - acknowledgment variant": "Mackerras-3-Clause-acknowledgment",
	"mackerras 3-clause license": "Mackerras-3-Clause",
	"magaz license": "magaz",
	"mailprio license": "mailprio",
	"makeindex license": "MakeIndex",
	"man2html license": "man2html",
	"martin birgmeier license": "Martin-Birgmeier",
	"matrix template library license": "MTLL",
	"mcphee slideshow license": "McPhee-slideshow",
	"metamail license": "metamail",
	"michigan/merit networks license": "UMich-Merit",
	"microsoft limited public license": "MS-LPL",
	"microsoft public license": "MS-PL",
	"microsoft reciprocal license": "MS-RL",
	"minecraft mod public license v1.0.1": "MMPL-1.0.1",
	"minpack license": "Minpack",
	"mips license": "MIPS",
	"mit +no-false-attribs license": "MITNFA",
	"mit click license": "MIT-Click",
	"mit festival variant": "MIT-Festival",
	"mit khronos - old variant": "MIT-Khronos-old",
	"mit license": "MIT",
	"mit license modern variant": "MIT-Modern-Variant",
	"mit no attribution": "MIT-0",
	"mit open group variant": "MIT-open-group",
	"mit testregex variant": "MIT-testregex",
	"mit tom wu variant": "MIT-Wu",
	"mit-stk license": "MIT-STK",
	"mmixware license": "MMIXware",
	"motosoto license": "Motosoto",
	"mozilla public license 1.0": "MPL-1.0",
	"mozilla public license 1.1": "MPL-1.1",
	"mozilla public license 2.0": "MPL-2.0",
	"mozilla public license 2.0 (no copyleft exception)": "MPL-2.0-no-copyleft-exception",
	"mpeg software simulation": "MPEG-SSG",
	"mpi permissive license": "mpi-permissive",
	"mpich2 license": "mpich2",
	"mplus font license": "mplus",
	"mulan permissive software license, version 1": "MulanPSL-1.0",
	"mulan permissive software license, version 2": "MulanPSL-2.0",
	"multics license": "Multics",
	"mup license": "Mup",
	"nara institute of science and technology license (2003)": "NAIST-2003",
	"nasa open source agreement 1.3": "NASA-1.3",
	"naumen public license": "Naumen",
	"ncbi public domain notice": "NCBI-PD",
	"ncl source code license": "NCL",
	"net boolean public license v1": "NBPL-1.0",
	"net-snmp license": "Net-SNMP",
	"netcdf license": "NetCDF",
	"nethack general public license": "NGPL",
	"netizen open source license": "NOSL",
	"netscape public license v1.0": "NPL-1.0",
	"netscape public license v1.1": "NPL-1.1",
	"newsletr license": "Newsletr",
	"ngrep license": "ngrep",
	"nicta public software license, version 1.0": "NICTA-1.0",
	"nist    public domain notice tnt variant": "NIST-PD-TNT",
	"nist public domain notice": "NIST-PD",
	"nist public domain notice with license fallback": "NIST-PD-fallback",
	"nist software license": "NIST-Software",
	"no limit public license": "NLPL",
	"nokia open source license": "Nokia",
	"non-commercial government licence": "NCGL-UK-2.0",
	"non-profit open software license 3.0": "NPOSL-3.0",
	"norwegian licence for open government data (nlod) 1.0": "NLOD-1.0",
	"norwegian licence for open government data (nlod) 2.0": "NLOD-2.0",
	"noweb license": "Noweb",
	"nrl license": "NRL",
	"ntia public domain notice": "NTIA-PD",
	"ntp license": "NTP",
	"ntp no attribution": "NTP-0",
	"nunit license": "Nunit",
	"oar license": "OAR",
	"oclc research public license 2.0": "OCLC-2.0",
	"offis license": "OFFIS",
	"ogc software license, version 1.0": "OGC-1.0",
	"open cascade technology public license": "OCCT-PL",
	"open data commons attribution license v1.0": "ODC-By-1.0",
	"open data commons open database license v1.0": "ODbL-1.0",
	"open data commons public domain dedication & license 1.0": "PDDL-1.0",
	"open government licence - canada": "OGL-Canada-2.0",
	"open government licence v1.0": "OGL-UK-1.0",
	"open government licence v2.0": "OGL-UK-2.0",
	"open government licence v3.0": "OGL-UK-3.0",
	"open group test suite license": "OGTSL",
	"open ldap public license 2.2.2": "OLDAP-2.2.2",
	"open ldap public license v1.1": "OLDAP-1.1",
	"open ldap public license v1.2": "OLDAP-1.2",
	"open ldap public license v1.3": "OLDAP-1.3",
	"open ldap public license v1.4": "OLDAP-1.4",
	"open ldap public license v2.0 (or possibly 2.0a and 2.0b)": "OLDAP-2.0",
	"open ldap public license v2.0.1": "OLDAP-2.0.1",
	"open ldap public license v2.1": "OLDAP-2.1",
	"open ldap public license v2.2": "OLDAP-2.2",
	"open ldap public license v2.2.1": "OLDAP-2.2.1",
	"open ldap public license v2.3": "OLDAP-2.3",
	"open ldap public license v2.4": "OLDAP-2.4",
	"open ldap public license v2.5": "OLDAP-2.5",
	"open ldap public license v2.6": "OLDAP-2.6",
	"open ldap public license v2.7": "OLDAP-2.7",
	"open ldap public license v2.8": "OLDAP-2.8",
	"open logistics foundation license version 1.3": "OLFL-1.3",
	"open market license": "OML",
	"open public license v1.0": "OPL-1.0",
	"open publication license v1.0": "OPUBL-1.0",
	"open software license 1.0": "OSL-1.0",
	"open software license 1.1": "OSL-1.1",
	"open software license 2.0": "OSL-2.0",
	"open software license 2.1": "OSL-2.1",
	"open software license 3.0": "OSL-3.0",
	"open use of data agreement v1.0": "O-UDA-1.0",
	"openmdw license agreement v1.0": "OpenMDW-1.0",
	"openpbs v2.3 software license": "OpenPBS-2.3",
	"openssl license": "OpenSSL",
	"openssl license - standalone": "OpenSSL-standalone",
	"openvision license": "OpenVision",
	"osc license 1.0": "OSC-1.0",
	"oset public license version 2.1": "OSET-PL-2.1",
	"ossp license": "OSSP",
	"padl license": "PADL",
	"paratype free font licensing agreement v1.3": "ParaType-Free-Font-1.3",
	"peer production license": "PPL",
	"php license v3.0": "PHP-3.0",
	"php license v3.01": "PHP-3.01",
	"pixar license": "Pixar",
	"pkgconf license": "pkgconf",
	"plexus classworlds license": "Plexus",
	"png reference library license v1 (for libpng 0.5 through 1.6.35)": "libpng-1.6.35",
	"png reference library version 2": "libpng-2.0",
	"pnmstitch license": "pnmstitch",
	"polyform noncommercial license 1.0.0": "PolyForm-Noncommercial-1.0.0",
	"polyform small business license 1.0.0": "PolyForm-Small-Business-1.0.0",
	"postgresql license": "PostgreSQL",
	"psfrag license": "psfrag",
	"psutils license": "psutils",
	"python ldap license": "python-ldap",
	"python license 2.0": "Python-2.0",
	"python license 2.0.1": "Python-2.0.1",
	"python software foundation license 2.0": "PSF-2.0",
	"q public license 1.0": "QPL-1.0",
	"q public license 1.0 - inria 2004 variant": "QPL-1.0-INRIA-2004",
	"qhull license": "Qhull",
	"radvd license": "radvd",
	"rdisc license": "Rdisc",
	"realnetworks public source license v1.0": "RPSL-1.0",
	"reciprocal public license 1.1": "RPL-1.1",
	"reciprocal public license 1.5": "RPL-1.5",
	"red hat ecos public license v1.1": "RHeCos-1.1",
	"ricoh source code public license": "RSCPL",
	"rsa message-digest license": "RSA-MD",
	"ruby license": "Ruby",
	"ruby pty extension license": "Ruby-pty",
	"sax public domain notice": "SAX-PD",
	"sax public domain notice 2.0": "SAX-PD-2.0",
	"saxpath license": "Saxpath",
	"scea shared source license": "SCEA",
	"scheme language report license": "SchemeReport",
	"scheme widget library (swl) software license agreement": "SWL",
	"secure messaging protocol public license": "SMPPL",
	"sendmail license": "Sendmail",
	"sendmail license 8.23": "Sendmail-8.23",
	"sendmail open source license v1.1": "Sendmail-Open-Source-1.1",
	"server side public license, v 1": "SSPL-1.0",
	"sgi free software license b v1.0": "SGI-B-1.0",
	"sgi free software license b v1.1": "SGI-B-1.1",
	"sgi free software license b v2.0": "SGI-B-2.0",
	"sgi opengl license": "SGI-OpenGL",
	"sgmlug parser materials license": "SGMLUG-PM",
	"sgp4 permission notice": "SGP4",
	"sil open font license 1.0": "OFL-1.0",
	"sil open font license 1.0 with no reserved font name": "OFL-1.0-no-RFN",
	"sil open font license 1.0 with reserved font name": "OFL-1.0-RFN",
	"sil open font license 1.1": "OFL-1.1",
	"sil open font license 1.1 with no reserved font name": "OFL-1.1-no-RFN",
	"sil open font license 1.1 with reserved font name": "OFL-1.1-RFN",
	"simple public license 2.0": "SimPL-2.0",
	"sl license": "SL",
	"sleepycat license": "Sleepycat",
	"smail general public license": "SMAIL-GPL",
	"snia public license 1.1": "SNIA",
	"snprintf license": "snprintf",
	"sofa software license": "SOFA",
	"softsurfer license": "softSurfer",
	"solderpad hardware license v0.5": "SHL-0.5",
	"solderpad hardware license, version 0.51": "SHL-0.51",
	"soundex license": "Soundex",
	"spencer license 86": "Spencer-86",
	"spencer license 94": "Spencer-94",
	"spencer license 99": "Spencer-99",
	"sqlite blessing": "blessing",
	"ssh openssh license": "SSH-OpenSSH",
	"ssh short notice": "SSH-short",
	"ssh-keyscan license": "ssh-keyscan",
	"ssleay license - standalone": "SSLeay-standalone",
	"standard ml of new jersey license": "SMLNJ",
	"sugarcrm public license v1.1.3": "SugarCRM-1.1.3",
	"sun industry standards source license v1.1": "SISSL",
	"sun industry standards source license v1.2": "SISSL-1.2",
	"sun ppp license": "Sun-PPP",
	"sun ppp license (2000)": "Sun-PPP-2000",
	"sun public license v1.0": "SPL-1.0",
	"sunpro license": "SunPro",
	"sustainable use license v1.0": "SUL-1.0",
	"swrule license": "swrule",
	"sybase open watcom public license 1.0": "Watcom-1.0",
	"symlinks license": "Symlinks",
	"systemics bsd variant license": "BSD-Systemics",
	"systemics w3works bsd variant license": "BSD-Systemics-W3Works",
	"taiwan open government data license, version 1.0": "OGDL-Taiwan-1.0",
	"tapr open hardware license v1.0": "TAPR-OHL-1.0",
	"tcl/tk license": "TCL",
	"tcp wrappers license": "TCP-wrappers",
	"technische universitaet berlin license 1.0": "TU-Berlin-1.0",
	"technische universitaet berlin license 2.0": "TU-Berlin-2.0",
	"tekhvc license": "TekHVC",
	"termreadkey license": "TermReadKey",
	"text-tabs+wrap license": "TTWL",
	"the miros licence": "MirOS",
	"the parity public license 6.0.0": "Parity-6.0.0",
	"the parity public license 7.0.0": "Parity-7.0.0",
	"the unlicense": "Unlicense",
	"thirdeye license": "ThirdEye",
	"thor public license 1.0": "TPL-1.0",
	"threeparttable license": "threeparttable",
	"time::parsedate license": "TPDL",
	"tmate open source license": "TMate",
	"torque v2.5+ software license v1.1": "TORQUE-1.1",
	"transitive grace period public licence 1.0": "TGPPL-1.0",
	"trusster open source license": "TOSL",
	"trustedqsl license": "TrustedQSL",
	"ttyp0 license": "TTYP0",
	"ubuntu font licence v1.0": "Ubuntu-font-1.0",
	"ucar license": "UCAR",
	"ulem license": "ulem",
	"unicode license agreement - data files and software (2015)": "Unicode-DFS-2015",
	"unicode license agreement - data files and software (2016)": "Unicode-DFS-2016",
	"unicode license v3": "Unicode-3.0",
	"unicode terms of use": "Unicode-TOU",
	"united    kingdom open parliament licence v3.0": "OPL-UK-3.0",
	"universal permissive license v1.0": "UPL-1.0",
	"university of illinois/ncsa open source license": "NCSA",
	"unixcrypt license": "UnixCrypt",
	"unlicense - libtelnet variant": "Unlicense-libtelnet",
	"unlicense - libwhirlpool variant": "Unlicense-libwhirlpool",
	"unrar license": "UnRAR",
	"upstream compatibility license v1.0": "UCL-1.0",
	"utah raster toolkit run length encoded license": "URT-RLE",
	"vim license": "Vim",
	"vixie cron license": "Vixie-Cron",
	"vostrom public license for open source": "VOSTROM",
	"vovida software license v1.0": "VSL-1.0",
	"w3c software notice and document license (2015-05-13)": "W3C-20150513",
	"w3c software notice and license (1998-07-20)": "W3C-19980720",
	"w3c software notice and license (2002-12-31)": "W3C",
	"w3m license": "w3m",
	"widget workshop license": "Widget-Workshop",
	"wordnet license": "WordNet",
	"wsuipa license": "Wsuipa",
	"wwl license": "wwl",
	"wxwindows library license": "wxWindows",
	"x.net license": "Xnet",
	"x11 license": "X11",
	"x11 license distribution modification variant": "X11-distribute-modifications-variant",
	"x11 no permit persons clause": "X11-no-permit-persons",
	"x11 swapped final paragraphs": "X11-swapped",
	"xdebug license v 1.03": "Xdebug-1.03",
	"xerox license": "Xerox",
	"xfig license": "Xfig",
	"xfree86 license 1.1": "XFree86-1.1",
	"xinetd license": "xinetd",
	"xkeyboard-config zinoviev license": "xkeyboard-config-Zinoviev",
	"xlock license": "xlock",
	"xpp license": "xpp",
	"xskat license": "XSkat",
	"xzoom license": "xzoom",
	"yahoo! public license v1.0": "YPL-1.0",
	"yahoo! public license v1.1": "YPL-1.1",
	"zed license": "Zed",
	"zeeff license": "Zeeff",
	"zend license v2.0": "Zend-2.0",
	"zimbra public license v1.3": "Zimbra-1.3",
	"zimbra public license v1.4": "Zimbra-1.4",
	"zlib license": "Zlib",
	"zlib/libpng license with acknowledgement": "zlib-acknowledgement",
	"zope public license 1.1": "ZPL-1.1",
	"zope public license 2.0": "ZPL-2.0",
	"zope public license 2.1": "ZPL-2.1",
}
